/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainApp;

/**
 *
 * @author hp
 */
public class GenerateReport extends javax.swing.JFrame {

    /**
     * Creates new form GenerateReprot
     */
    public GenerateReport() {
        initComponents();
        
        // Initialize All Filters As Disabled
        setModelFilterStatus(false);
        setPriceFilterStatus(false);
    }
    
    private void setModelFilterStatus(boolean status) {
        ModelNameLabel.setEnabled(status);
        ModelNameField.setEnabled(status);
    }
    
    private void setPriceFilterStatus(boolean status) {
        PriceRangeLabel.setEnabled(status);
        PriceRange_to.setEnabled(status);
        LowerBoundPriceField.setEnabled(status);
        UpperBoundPriceField.setEnabled(status);
    }
    
    private void UpdateTableFromPriceRange() {
        // Check If Lower Bound Is Lower Than Higher Bound, If not, exit immediately
        
        // Remove All Contents From JTable
        // Loop All Contents then Check those who have matched Within or Equal the Lower and Higher Bound Prices
        // Add Filtered Contents to JTable
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ModelNameField = new javax.swing.JTextField();
        LowerBoundPriceField = new javax.swing.JTextField();
        UpperBoundPriceField = new javax.swing.JTextField();
        FilterChoiceLabel = new javax.swing.JLabel();
        ModelNameLabel = new javax.swing.JLabel();
        PriceRangeLabel = new javax.swing.JLabel();
        PriceRange_to = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        FilterChoice = new javax.swing.JComboBox<>();
        ModelNameLabel1 = new javax.swing.JLabel();
        ModelNameField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Car Name", "Car Model", "Car Description", "Rent Price", "Status", "Date Available"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        ModelNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ModelNameFieldKeyTyped(evt);
            }
        });

        LowerBoundPriceField.setText("00");
        LowerBoundPriceField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LowerBoundPriceFieldKeyTyped(evt);
            }
        });

        UpperBoundPriceField.setText("00");
        UpperBoundPriceField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UpperBoundPriceFieldKeyTyped(evt);
            }
        });

        FilterChoiceLabel.setText("Filter By:");

        ModelNameLabel.setText("Model Name:");

        PriceRangeLabel.setText("Price Range:");

        PriceRange_to.setText("to");

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Generate Report");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );

        FilterChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Model Name", "Price Range" }));
        FilterChoice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FilterChoiceItemStateChanged(evt);
            }
        });

        ModelNameLabel1.setText("Model Name:");

        ModelNameField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ModelNameField1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(FilterChoiceLabel)
                .addGap(27, 27, 27)
                .addComponent(FilterChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ModelNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModelNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ModelNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModelNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PriceRangeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LowerBoundPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(PriceRange_to)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpperBoundPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModelNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LowerBoundPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpperBoundPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FilterChoiceLabel)
                    .addComponent(ModelNameLabel)
                    .addComponent(PriceRangeLabel)
                    .addComponent(PriceRange_to)
                    .addComponent(FilterChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ModelNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ModelNameLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FilterChoiceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FilterChoiceItemStateChanged
        // TODO add your handling code here:
        switch (FilterChoice.getSelectedIndex()) {
            case 0:
                setModelFilterStatus(true);
                setPriceFilterStatus(false);
                break;
            case 1:
                setModelFilterStatus(false);
                setPriceFilterStatus(true);
                break;
        }
        
        // <OPTIONAL TODO>: Reset Table Contents To Unfiltered
    }//GEN-LAST:event_FilterChoiceItemStateChanged

    private void ModelNameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModelNameFieldKeyTyped
        // TODO add your handling code here:
        
        // TODO: Update Table Contents through Filtering
        // Get "Word Filter"
        // Remove All Contents From JTable
        // Loop All Contents then Check those who have matched "Word Filter"
        // Add Filtered Contents to JTable
    }//GEN-LAST:event_ModelNameFieldKeyTyped

    private void LowerBoundPriceFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LowerBoundPriceFieldKeyTyped
        // TODO add your handling code here:
        // Only Call The Function Below If Inputs Are Checked To Be All Number
        UpdateTableFromPriceRange();
    }//GEN-LAST:event_LowerBoundPriceFieldKeyTyped

    private void UpperBoundPriceFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UpperBoundPriceFieldKeyTyped
        // TODO add your handling code here:
        // Only Call The Function Below If Inputs Are Checked To Be All Number
        UpdateTableFromPriceRange();
    }//GEN-LAST:event_UpperBoundPriceFieldKeyTyped

    private void ModelNameField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModelNameField1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ModelNameField1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FilterChoice;
    private javax.swing.JLabel FilterChoiceLabel;
    private javax.swing.JTextField LowerBoundPriceField;
    private javax.swing.JTextField ModelNameField;
    private javax.swing.JTextField ModelNameField1;
    private javax.swing.JLabel ModelNameLabel;
    private javax.swing.JLabel ModelNameLabel1;
    private javax.swing.JLabel PriceRangeLabel;
    private javax.swing.JLabel PriceRange_to;
    private javax.swing.JTextField UpperBoundPriceField;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
